flags:
  cassava:
    bytestring--lt-0_10_4: false
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- .
extra-deps:
- git: https://github.com/neongreen/formatting
  commit: 0532d763ab593c60c77b2c377d5e633af3b9f3c8
- Glob-0.9.2
- HUnit-1.6.0.0
- Only-0.1
- QuickCheck-2.11.3
- abstract-deque-0.3
- abstract-par-0.3.3
- aeson-1.3.0.0
- ansi-terminal-0.8.0.2
- ansi-wl-pprint-0.6.8.2
- attoparsec-0.13.2.2
- base-compat-0.9.3
- base-orphans-0.7
- base-prelude-1.2.0.1
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- call-stack-0.1.0
- cassava-0.5.1.0
- cereal-0.5.5.0
- clock-0.7.2
- code-page-0.1.3
- colour-2.3.4
- cpphs-1.20.8
- criterion-1.4.0.0
- dlist-0.8.0.4
- erf-2.0.0.0
- exceptions-0.10.0
- hashable-1.2.7.0
- haskell-src-exts-1.20.2
- haskell-src-meta-0.8.0.2@rev:1
- hspec-2.5.0
- hspec-core-2.5.0
- hspec-discover-2.5.0
- hspec-expectations-0.8.2
- integer-logarithms-1.0.2.1
- interpolate-0.2.0
- js-flot-0.8.3
- js-jquery-3.3.1
- math-functions-0.2.1.0
- microlens-0.4.9
- microstache-1.0.1.1
- monad-par-0.3.4.8
- monad-par-extras-0.3.3
- mwc-random-0.13.6.0
- neat-interpolation-0.3.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.14.2.0
- parallel-3.2.1.1
- polyparse-1.12
- primitive-0.6.3.0
- quickcheck-io-0.2.0
- random-1.1
- safe-0.3.17
- scientific-0.3.5.3
- semigroups-0.18.4
- setenv-0.1.1.3
- statistics-0.14.0.2
- syb-0.7
- tagged-0.8.5
- text-short-0.1.2
- tf-random-0.5
- th-abstraction-0.2.6.0
- th-expand-syns-0.4.4.0
- th-lift-0.7.8
- th-lift-instances-0.1.11
- th-orphans-0.13.5
- th-reify-many-0.1.8
- time-locale-compat-0.1.1.3
- transformers-compat-0.6.0.6
- unordered-containers-0.2.9.0
- uuid-types-1.0.3
- vector-0.12.0.1
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.4
- vector-th-unbox-0.2.1.6
resolver: ghc-8.4
